# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-10 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20190204_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.TextField(blank=True, max_length=264),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.TextField(blank=True, max_length=264),
        ),
    ]
