# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-10 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20190210_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='sample',
            field=models.TextField(default='hi', max_length=264),
        ),
    ]
